image:
  repository: public.ecr.aws/z6g0f8n7/sidecar
  pullPolicy: Always
  tag: "v1.0.0-beta.5"

sidecar:
  replicas: 1
  nameOverride: ''
  additionalLabels: {}
  args: ["run"]
  env:
    SIDECAR_CHAIN: "mainnet"
    SIDECAR_DEBUG: "false"
    SIDECAR_ETHEREUM_RPC_URL: ""
    SIDECAR_DATABASE_HOST: ""
    SIDECAR_DATABASE_PORT: "5432"
    SIDECAR_DATABASE_USER: "sidecar"
    SIDECAR_DATABASE_DB_NAME: "sidecar"
    # SIDECAR_STATSD_URL: ""
    # Datadog APM - using TCP instead of Unix socket for security Finding.
    DD_AGENT_HOST: "datadog-agent"
    DD_TRACE_AGENT_PORT: "8126"
  additionalEnv: []
  #  - name: ENV_NAME
  #    value: "env value"
  ports:
    - name: grpc
      port: 7100
      targetPort: 7100
      protocol: TCP
    - name: http
      port: 7101
      targetPort: 7101
      protocol: TCP
  resources: {}
  metadataLabels: {}
  serviceAccount:
    name: default
  secret:
    name: sidecar-secrets
    data: {}
    # SIDECAR_DATABASE_PASSWORD: ""
  service:
    enabled: true
  ingress:
    grpc:
      enabled: false
      hostname: ""
    http:
      enabled: false

