import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "public-api/eigenlayer-public-api-specification",
    },
    {
      type: "category",
      label: "health",
      link: {
        type: "doc",
        id: "public-api/health",
      },
      items: [
        {
          type: "doc",
          id: "public-api/health-health-check",
          label: "HealthCheck",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "rewards",
      link: {
        type: "doc",
        id: "public-api/rewards",
      },
      items: [
        {
          type: "doc",
          id: "public-api/rewards-generate-claim-proof",
          label: "GenerateClaimProof",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "public-api/rewards-list-distribution-roots",
          label: "ListDistributionRoots",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "public-api/rewards-get-summarized-rewards-for-earner",
          label: "GetSummarizedRewardsForEarner",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "public-api/schemas/aboutrequest",
          label: "AboutRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/aboutresponse",
          label: "AboutResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/attributablereward",
          label: "AttributableReward",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/avsoperatorstatechange",
          label: "AvsOperatorStateChange",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/avsreward",
          label: "AvsReward",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/backfillstakeroperatorsrequest",
          label: "BackfillStakerOperatorsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/backfillstakeroperatorsresponse",
          label: "BackfillStakerOperatorsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/block",
          label: "Block",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/claimedreward",
          label: "ClaimedReward",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/disableddistributionroot",
          label: "DisabledDistributionRoot",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/distributionroot",
          label: "DistributionRoot",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/earnerleaf",
          label: "EarnerLeaf",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/eigenstatechange",
          label: "EigenStateChange",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/generateclaimproofrequest",
          label: "GenerateClaimProofRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/generateclaimproofresponse",
          label: "GenerateClaimProofResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/generaterewardsrequest",
          label: "GenerateRewardsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/generaterewardsresponse",
          label: "GenerateRewardsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/generaterewardsrootrequest",
          label: "GenerateRewardsRootRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/generaterewardsrootresponse",
          label: "GenerateRewardsRootResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/generatestakeroperatorsrequest",
          label: "GenerateStakerOperatorsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/generatestakeroperatorsresponse",
          label: "GenerateStakerOperatorsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getattributablerewardsfordistributionrootrequest",
          label: "GetAttributableRewardsForDistributionRootRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getattributablerewardsfordistributionrootresponse",
          label: "GetAttributableRewardsForDistributionRootResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getattributablerewardsforsnapshotrequest",
          label: "GetAttributableRewardsForSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getattributablerewardsforsnapshotresponse",
          label: "GetAttributableRewardsForSnapshotResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getavailablerewardstokensrequest",
          label: "GetAvailableRewardsTokensRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getavailablerewardstokensresponse",
          label: "GetAvailableRewardsTokensResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getblockheightrequest",
          label: "GetBlockHeightRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getblockheightresponse",
          label: "GetBlockHeightResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getclaimablerewardsrequest",
          label: "GetClaimableRewardsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getclaimablerewardsresponse",
          label: "GetClaimableRewardsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getclaimedrewardsbyblockrequest",
          label: "GetClaimedRewardsByBlockRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getclaimedrewardsbyblockresponse",
          label: "GetClaimedRewardsByBlockResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getdailyaprforearnerstrategyrequest",
          label: "GetDailyAprForEarnerStrategyRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getdailyaprforearnerstrategyresponse",
          label: "GetDailyAprForEarnerStrategyResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getdailyoperatorstrategyaprsrequest",
          label: "GetDailyOperatorStrategyAprsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getdailyoperatorstrategyaprsresponse",
          label: "GetDailyOperatorStrategyAprsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getdelegatedstakersforoperatorrequest",
          label: "GetDelegatedStakersForOperatorRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getdelegatedstakersforoperatorresponse",
          label: "GetDelegatedStakersForOperatorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getdelegatedstrategiesforoperatorrequest",
          label: "GetDelegatedStrategiesForOperatorRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getdelegatedstrategiesforoperatorresponse",
          label: "GetDelegatedStrategiesForOperatorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/geteigenstatechangesrequest",
          label: "GetEigenStateChangesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/geteigenstatechangesresponse",
          label: "GetEigenStateChangesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getoperatordelegatedstakeforstrategyrequest",
          label: "GetOperatorDelegatedStakeForStrategyRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getoperatordelegatedstakeforstrategyresponse",
          label: "GetOperatorDelegatedStakeForStrategyResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getregisteredavsforoperatorrequest",
          label: "GetRegisteredAvsForOperatorRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getregisteredavsforoperatorresponse",
          label: "GetRegisteredAvsForOperatorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getrewardsbyavsfordistributionrootrequest",
          label: "GetRewardsByAvsForDistributionRootRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getrewardsbyavsfordistributionrootresponse",
          label: "GetRewardsByAvsForDistributionRootResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getrewardsforsnapshotrequest",
          label: "GetRewardsForSnapshotRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getrewardsforsnapshotresponse",
          label: "GetRewardsForSnapshotResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getrewardsrootrequest",
          label: "GetRewardsRootRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getrewardsrootresponse",
          label: "GetRewardsRootResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getstakersharesrequest",
          label: "GetStakerSharesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getstakersharesresponse",
          label: "GetStakerSharesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getstaterootrequest",
          label: "GetStateRootRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getstaterootresponse",
          label: "GetStateRootResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getstrategyforstakerrequest",
          label: "GetStrategyForStakerRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getstrategyforstakerresponse",
          label: "GetStrategyForStakerResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getsummarizedrewardsforearnerrequest",
          label: "GetSummarizedRewardsForEarnerRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/getsummarizedrewardsforearnerresponse",
          label: "GetSummarizedRewardsForEarnerResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/gettotalclaimedrewardsrequest",
          label: "GetTotalClaimedRewardsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/gettotalclaimedrewardsresponse",
          label: "GetTotalClaimedRewardsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/healthcheckrequest",
          label: "HealthCheckRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/healthcheckresponse",
          label: "HealthCheckResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/historicalreward",
          label: "HistoricalReward",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/historicalreward-historicalrewardamount",
          label: "HistoricalReward_HistoricalRewardAmount",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/int-64-value",
          label: "Int64Value",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listavsoperatorsetslashinghistoryrequest",
          label: "ListAvsOperatorSetSlashingHistoryRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listavsoperatorsetslashinghistoryresponse",
          label: "ListAvsOperatorSetSlashingHistoryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listavsslashinghistoryrequest",
          label: "ListAvsSlashingHistoryRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listavsslashinghistoryresponse",
          label: "ListAvsSlashingHistoryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listclaimedrewardsbyblockrangerequest",
          label: "ListClaimedRewardsByBlockRangeRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listclaimedrewardsbyblockrangeresponse",
          label: "ListClaimedRewardsByBlockRangeResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listdistributionrootsrequest",
          label: "ListDistributionRootsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listdistributionrootsresponse",
          label: "ListDistributionRootsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listearnerhistoricalrewardsrequest",
          label: "ListEarnerHistoricalRewardsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listearnerhistoricalrewardsresponse",
          label: "ListEarnerHistoricalRewardsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listearnerlifetimerewardsrequest",
          label: "ListEarnerLifetimeRewardsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listearnerlifetimerewardsresponse",
          label: "ListEarnerLifetimeRewardsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorqueuedwithdrawalsrequest",
          label: "ListOperatorQueuedWithdrawalsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorqueuedwithdrawalsresponse",
          label: "ListOperatorQueuedWithdrawalsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorslashinghistoryrequest",
          label: "ListOperatorSlashingHistoryRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorslashinghistoryresponse",
          label: "ListOperatorSlashingHistoryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorstrategyqueuedwithdrawalsrequest",
          label: "ListOperatorStrategyQueuedWithdrawalsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorstrategyqueuedwithdrawalsresponse",
          label: "ListOperatorStrategyQueuedWithdrawalsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorsforavsrequest",
          label: "ListOperatorsForAvsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorsforavsresponse",
          label: "ListOperatorsForAvsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorsforstakerrequest",
          label: "ListOperatorsForStakerRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorsforstakerresponse",
          label: "ListOperatorsForStakerResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorsforstrategyrequest",
          label: "ListOperatorsForStrategyRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/listoperatorsforstrategyresponse",
          label: "ListOperatorsForStrategyResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststakerqueuedwithdrawalsrequest",
          label: "ListStakerQueuedWithdrawalsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststakerqueuedwithdrawalsresponse",
          label: "ListStakerQueuedWithdrawalsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststakerslashinghistoryrequest",
          label: "ListStakerSlashingHistoryRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststakerslashinghistoryresponse",
          label: "ListStakerSlashingHistoryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststakerstrategiesrequest",
          label: "ListStakerStrategiesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststakerstrategiesresponse",
          label: "ListStakerStrategiesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststrategiesrequest",
          label: "ListStrategiesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststrategiesresponse",
          label: "ListStrategiesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststrategyqueuedwithdrawalsrequest",
          label: "ListStrategyQueuedWithdrawalsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/liststrategyqueuedwithdrawalsresponse",
          label: "ListStrategyQueuedWithdrawalsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/operator",
          label: "Operator",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/operatorset",
          label: "OperatorSet",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/operatorsharedelta",
          label: "OperatorShareDelta",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/operatorstrategyapr",
          label: "OperatorStrategyApr",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/pagination",
          label: "Pagination",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/proof",
          label: "Proof",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/queuestakerstrategywithdrawal",
          label: "QueueStakerStrategyWithdrawal",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/queuedstrategywithdrawal",
          label: "QueuedStrategyWithdrawal",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/readyrequest",
          label: "ReadyRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/readyresponse",
          label: "ReadyResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/reward",
          label: "Reward",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/rewardamount",
          label: "RewardAmount",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/rewardsubmission",
          label: "RewardSubmission",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/rewardtype",
          label: "RewardType",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/slashedstaker",
          label: "SlashedStaker",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/slashingevent",
          label: "SlashingEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/slashingevent-operatorset",
          label: "SlashingEvent_OperatorSet",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/slashingevent-strategy",
          label: "SlashingEvent_Strategy",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/stakerdelegationchange",
          label: "StakerDelegationChange",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/stakershare",
          label: "StakerShare",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/stakersharedelta",
          label: "StakerShareDelta",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/stakerslashingevent",
          label: "StakerSlashingEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/stakerstrategy",
          label: "StakerStrategy",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/stakerwithdrawal",
          label: "StakerWithdrawal",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/stateroot",
          label: "StateRoot",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/strategy",
          label: "Strategy",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/streameigenstatechangesrequest",
          label: "StreamEigenStateChangesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/streameigenstatechangesresponse",
          label: "StreamEigenStateChangesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/streamindexedblocksrequest",
          label: "StreamIndexedBlocksRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/streamindexedblocksrequest-filters",
          label: "StreamIndexedBlocksRequest_Filters",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/streamindexedblocksresponse",
          label: "StreamIndexedBlocksResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/submitteddistributionroot",
          label: "SubmittedDistributionRoot",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/summarizedearnerreward",
          label: "SummarizedEarnerReward",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/tokenleaf",
          label: "TokenLeaf",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/totalclaimedreward",
          label: "TotalClaimedReward",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/transaction",
          label: "Transaction",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/transactionlog",
          label: "TransactionLog",
          className: "schema",
        },
        {
          type: "doc",
          id: "public-api/schemas/transactionmetadata",
          label: "TransactionMetadata",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
