/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
		type: "autogenerated",
		dirName: "sidecar",
	},
  ],
  publicApiSidebar: [
    {
      type: "category",
      label: "Public API",
      link: {
        type: "generated-index",
        title: "Public API",
        description: "EigenLayer hosted Sidecar API",
        slug: "/category/public-api"
      },
      items: require("./docs/public-api/sidebar.js")
    }
  ],
	fullApiSidebar: [
		{
			type: "category",
			label: "Full API",
			link: {
				type: "generated-index",
				title: "Full API",
				description: "EigenLayer Sidecar API",
				slug: "/category/api"
			},
			items: require("./docs/api/sidebar.js")
		}
	]
};

export default sidebars;
